---
- name: "P1 - Testing RESTCONF"
  hosts: cisco
  connection: local
  tasks:
    - name: "P1T1 - Pull ACL Info"
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/restconf/data/native/router"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        return_content: true
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false
      register: p1t1_result

    - name: "P1T2 - Print ACL Info"
      ansible.builtin.debug:
        var: p1t1_result.json
