---
# ospf:
#   rid: "1.1.1.1"
#   area: 0
#   originate: true
#   networks:
#     - address: "10.0.10.0"
#       area: "0"
#       wildcard_bits: "0.0.0.3"
#     - address: "1.1.1.1"
#       area: "0"
#       wildcard_bits: "0.0.0.0"
#     - address: "8.8.8.8"
#       area: "0"
#       wildcard_bits: "0.0.0.0"

ospf_configure:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 1
          network:
          - area: 51
            ip: 1.1.1.1
            wildcard: 255.255.255.255
          - area: 0
            ip: 192.168.50.0
            wildcard: 255.255.255.0
          router-id: 1.1.1.1


bgp:
  asn: 1
  rid: "1.1.1.1"
  peers:
    - neighbor: "10.0.10.2"
      peer_asn: "2"
  networks:
    - network: "8.8.8.8"
      mask: "255.255.255.255"

syslog:
  hosts:
    - ip: "1.1.1.1"
    - ip: "2.2.2.2"
      port: "1234"
    - ip: "3.3.3.3"
    - ip: "4.4.4.4"
      port: "4567"

# bgp:
#   asn: "65001"
#   rid: "1.1.1.1"
#   peers:
#     - neighbor: "10.0.10.2"
#       peer_asn: "65001"

#     - neighbor: "10.0.10.6"
#       peer_asn: "65001"

#     - neighbor: "10.0.10.10"
#       peer_asn: "65001"
#   networks:
#     - network: "1.1.1.1"
#       mask: "255.255.255.255"

# eigrp:
#   style: "named"
#   asn: "1"
#   rid: "1.1.1.1"
#   networks:
#     - "1.1.1.1 0.0.0.0"

# ntp:
#   servers:
#     - "11.11.11.11"
#     - "22.22.22.22"
#     - "33.33.33.33"
